[tool.poetry]
name = "openeo-processes-dask"
version = "0.1.0"
description = ""
authors = ["Lukas Weidenholzer <lukas.weidenholzer@eodc.eu>"]
license = "Apache 2.0"
readme = "README.md"
repository = "https://github.com/Open-EO/openeo-processes-dask"
classifiers = [
    "Development Status :: 1 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache 2.0",
    "Operating System :: Ubuntu",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Typing :: Typed",
]
packages = [
    {include = "openeo_processes", from = "src"}
]

[tool.poetry.dependencies]
python = "^3.8, <3.11"
# xarray = ">=2022.3.0"  # 2022.6.0 onwards breaks the current ufunc implementations
# dask = {extras = ["array"], version = "^2022.8.0"}
# distributed = "^2022.8.0"
# stackstac = { extras = ["viz"], version = "^0.4.2", optional = true }
# lz4 = "^4.0.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
# types-PyYAML = "^6.0"
# ipykernel = "^6.15.1"
# graphviz = "^0.20.1"
# pystac-client = "^0.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
