[tool.poetry]
name = "openeo-processes-dask"
version = "0.1.0"
description = ""
authors = ["Lukas Weidenholzer <lukas.weidenholzer@eodc.eu>"]
license = "Apache 2.0"
readme = "README.md"
repository = "https://github.com/Open-EO/openeo-processes-dask"
classifiers = [
    "Development Status :: 1 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache 2.0",
    "Operating System :: Ubuntu",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Typing :: Typed",
]

packages = [
    { include = "src/openeo_processes_dask" }
]


[tool.poetry.dependencies]
python = "^3.8, <3.11"
# stackstac = { extras = ["viz"], version = "^0.4.2", optional = true }
lz4 = "^4.0.2"
dask = {extras = ["array"], version = "^2022.8.0"}
stackstac = "^0.4.2"
distributed = "^2022.8.0"
pystac-client = "^0.4.0"

[tool.poetry.dev-dependencies]
# pytest = "^7.1.2"
# types-PyYAML = "^6.0"
# ipykernel = "^6.15.1"
# graphviz = "^0.20.1"
# pystac-client = "^0.4.0"
pytest = "^7.1.2"
ipykernel = "^6.15.1"
matplotlib = "^3.5.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
