[tool.poetry]
name = "openeo-processes-dask"
version = "0.1.0"
description = ""
authors = ["Lukas Weidenholzer <lukas.weidenholzer@eodc.eu>"]
license = "Apache 2.0"
readme = "README.md"
repository = "https://github.com/Open-EO/openeo-processes-dask"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache 2.0",
    "Operating System :: Ubuntu",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Typing :: Typed",
]

packages = [
    { include = "openeo_processes_dask" }
]


[tool.poetry.dependencies]
python = "^3.8, <3.10"
geopandas = "^0.12.1"
xarray = "^2022.11.0"
dask = "^2022.11.1"
rasterio = "^1.3.4"
dask-geopandas = "^0.2.0"
datacube = "^1.8.9"
xgboost = "^1.7.1"
rioxarray = "^0.13.1"
odc-algo = "^0.2.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
ipykernel = "^6.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
